### At the begginig a bit preprocessing of data: 

In [1]:
import numpy as np
import pandas as pd
import Bio as bio
from os import listdir
from os.path import isfile, join

In [2]:
csv_files = [f for f in listdir('csv_data') if isfile(join('csv_data', f))]
for i in range(len(csv_files)):
    csv_files[i] = 'csv_data/' + csv_files[i]
    
csv_files[0:5]

['csv_data/CLMD_trachomatis.csv',
 'csv_data/CLOS_difficile.csv',
 'csv_data/CMV_AD169.csv',
 'csv_data/CPBT_jejuni.csv',
 'csv_data/EBV_AG876.csv']

In [3]:
Proteins_data = pd.read_csv(csv_files.pop(0),  index_col=0)
#Proteins_data.head(20)

In [4]:
for x in csv_files:
    res_data = pd.read_csv(x,  index_col=0)
    Proteins_data = pd.concat([Proteins_data, res_data], ignore_index=True)

In [5]:
Proteins_data.head(5)

Organism                Protein             AA             AR  \
0  CLMD_trachomatis   sp|O84499|COAE_CHLTR  [-0.59015886]   [0.58428664]   
1  CLMD_trachomatis   sp|O84066|6PGD_CHLTR    [3.5086597]   [0.58629868]   
2  CLMD_trachomatis   sp|O84379|AAXC_CHLTR   [2.17373241]   [0.45536687]   
3  CLMD_trachomatis  sp|O84712|CLPP2_CHLTR   [1.94636546]  [-0.65746793]   
4  CLMD_trachomatis   sp|O84102|ACPS_CHLTR   [2.95473522]   [1.22175269]   

              AN             AD             AC             AQ             AE  \
0  [-0.59015886]   [4.10762314]   [0.58428664]  [-0.59015886]   [1.75873214]   
1  [-0.87488183]  [-0.87488183]  [-0.87488183]   [1.31688894]  [-0.14429158]   
2   [1.02815538]  [-0.11742165]  [-0.69021016]  [-0.69021016]  [-0.69021016]   
3   [0.64444876]   [0.64444876]  [-0.65746793]   [0.64444876]   [3.24828215]   
4  [-0.51122985]  [-0.51122985]  [-0.51122985]  [-0.51122985]   [1.22175269]   

              AG  ...             VL             VK             VM  \
0  [-0.59015886]  ...  [-0.59015886]   [0.58428664]  [-0.59015886]   
1   [2.04747919]  ...   [2.77806945]  [-0.14429158]  [-0.14429158]   
2   [2.17373241]  ...   [2.74652092]  [-0.11742165]   [0.45536687]   
3   [1.94636546]  ...  [-0.65746793]  [-0.65746793]   [0.64444876]   
4  [-0.51122985]  ...   [1.22175269]   [1.22175269]  [-0.51122985]   

              VF             VP             VS             VT             VW  \
0   [1.75873214]   [0.58428664]   [0.58428664]   [0.58428664]  [-0.59015886]   
1  [-0.87488183]  [-0.14429158]   [1.31688894]  [-0.87488183]  [-0.87488183]   
2  [-0.69021016]  [-0.69021016]  [-0.69021016]  [-0.11742165]  [-0.69021016]   
3  [-0.65746793]   [0.64444876]  [-0.65746793]  [-0.65746793]  [-0.65746793]   
4  [-0.51122985]   [1.22175269]   [1.22175269]  [-0.51122985]  [-0.51122985]   

              VY             VV  
0  [-0.59015886]   [1.75873214]  
1  [-0.14429158]  [-0.87488183]  
2  [-0.11742165]  [-0.11742165]  
3  [-0.65746793]   [0.64444876]  
4   [1.22175269]   [2.95473522]  

[5 rows x 402 columns]

In [6]:
# Be careful with your data

Data_anal = Proteins_data

labels_categorized = Data_anal[Data_anal.columns[0]].values
feature_matrix = Data_anal[Data_anal.columns[2:22]].values

feature_matrix[0]

# Oh gosh

array(['[-0.59015886]', '[0.58428664]', '[-0.59015886]', '[4.10762314]',
       '[0.58428664]', '[-0.59015886]', '[1.75873214]', '[-0.59015886]',
       '[0.58428664]', '[0.58428664]', '[0.58428664]', '[-0.59015886]',
       '[-0.59015886]', '[-0.59015886]', '[-0.59015886]', '[-0.59015886]',
       '[-0.59015886]', '[-0.59015886]', '[0.58428664]', '[-0.59015886]'],
      dtype=object)

In [7]:
#labels_categorized

In [8]:
# Making labels not categorized (slightly)

labels = []

for x in labels_categorized:
    if x == 'human_proteome':
        labels.append(1)
    else:
        labels.append(0)
        
Data_anal['Label'] = labels

In [9]:
labels.count(0)

32200

In [10]:
# Do not ask what is happening here
# Our data has some bad feature, there are always str(list(float)) construction (-_-)

for i in range(len(feature_matrix)):
    for j in range(len(feature_matrix[i])):
        string = feature_matrix[i][j].replace('[', '').replace(']', '')
        feature_matrix[i][j] = float(string)

In [11]:
feature_matrix[0]

array([-0.59015886, 0.58428664, -0.59015886, 4.10762314, 0.58428664,
       -0.59015886, 1.75873214, -0.59015886, 0.58428664, 0.58428664,
       0.58428664, -0.59015886, -0.59015886, -0.59015886, -0.59015886,
       -0.59015886, -0.59015886, -0.59015886, 0.58428664, -0.59015886],
      dtype=object)

In [16]:
feature_matrix

array([[-0.59015886, 0.58428664, -0.59015886, ..., -0.59015886,
        0.58428664, -0.59015886],
       [3.5086597, 0.58629868, -0.87488183, ..., -0.14429158,
        -0.87488183, 2.04747919],
       [2.17373241, 0.45536687, 1.02815538, ..., 1.02815538, -0.11742165,
        2.17373241],
       ...,
       [1.27295872, 1.27295872, -0.48284641, ..., -0.48284641,
        -0.48284641, 3.02876384],
       [1.98453076, 1.12728205, 0.27003334, ..., -0.58721536, 0.27003334,
        -0.58721536],
       [2.43483879, 0.07473657, -0.23994373, ..., -0.71196417,
        0.07473657, 2.59217893]], dtype=object)

### Looking at our data:

In [12]:
### Here is the place for your code!!!

### Starting to make base-line with easy methods:

In [20]:
# Importing SKlearn magic

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report

In [13]:
# Making 2 Train-Test split
# One (final_test_*) for the final test and second (test_*) for train-test

train_feature_matrix, test_feature_matrix,\
train_labels, test_labels = train_test_split(feature_matrix, labels, test_size=0.2, random_state=42)

In [14]:
# Data preprocessing
# We will just give it try
scaler = preprocessing.StandardScaler()
train_feature_matrix_scaled = scaler.fit_transform(train_feature_matrix)
test_feature_matrix_scaled = scaler.fit_transform(test_feature_matrix)
#print('t h e r e  i s  n o t h i n g  i n t e r e s t i n g')

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


#### Method 1: Random Forest

In [55]:
# Will try Random Forest

forest = RandomForestClassifier(n_estimators= 3000, max_depth=10, bootstrap='True')

In [28]:
# Training 
forest.fit(train_feature_matrix, train_labels)

RandomForestClassifier(bootstrap='True', class_weight=None, criterion='gini',
            max_depth=15, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
y_pred = forest.predict(test_feature_matrix)

In [30]:
print(classification_report(test_labels, y_pred, labels=[0, 1]))

              precision    recall  f1-score   support

           0       0.82      0.51      0.63      6330
           1       0.82      0.95      0.88     14980

   micro avg       0.82      0.82      0.82     21310
   macro avg       0.82      0.73      0.75     21310
weighted avg       0.82      0.82      0.81     21310



In [48]:
forest.score(test_feature_matrix, test_labels)

0.8208352885969029

In [49]:
prediction = forest.predict(test_feature_matrix)

f_1 = f1_score(prediction, test_labels)

print('F1-score = '+str(f_1))

F1-score = 0.8821313904667819


Maybe not the best result


In [ ]:
#Raw code

#parametrs = {'n_estimators':np.arange(4000, 6001, 1000)}
parametrs = {'max_features':['log2', 'sqrt', '10', '30']}
gs_forest = GridSearchCV(forest, parametrs, cv = 5, scoring = 'accuracy', n_jobs=-1)

gs_forest.fit(train_feature_matrix, train_labels)

In [ ]:
gs_forest.best_estimator_

#### Method 2: Logistic Regression

In [35]:
# Making LogRes class

lr_clf = LogisticRegression(max_iter=100000, solver='saga', tol=0.00001, penalty ='l2'\
                            , C=100, class_weight = { 1 : 1 , 0: 1})

In [36]:
# Fitting not preproccesed data

lr_clf.fit(train_feature_matrix, train_labels)

LogisticRegression(C=100, class_weight={1: 1, 0: 1}, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100000,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='saga', tol=1e-05, verbose=0, warm_start=False)

In [37]:
# Weights

lr_clf.coef_

array([[ 0.01851586, -0.18174556, -0.35999432, -0.38950807,  0.2657495 ,
        -0.01857409, -0.07691971, -0.16424495, -0.0693551 , -0.52315851,
        -0.19995228, -0.18236666, -0.27808052, -0.1355815 ,  0.13585265,
         0.10094773, -0.15269855, -0.18802809, -0.2483542 , -0.1401076 ]])

In [38]:
# Score for test (Accuracy and F1-score)

accuracy_log = lr_clf.score(test_feature_matrix, test_labels)

prediction = lr_clf.predict(test_feature_matrix)

f_1 = f1_score(prediction, test_labels)

print('Acuracy = '+str(accuracy_log))
print('F1 score  = '+str(f_1))

Acuracy = 0.7867198498357578
F1 score  = 0.8581239269548931


#### Method 3: SVM

In [39]:
# Making

svm_rbf = SVC(kernel='rbf', max_iter=20000, tol=0.0001, C=2, gamma=3)

parametrs_rbf = {'C':np.linspace(1, 20, 5), 'gamma':np.linspace(0, 10, 5)}

#grid_search_rbf = GridSearchCV(svm_rbf, parametrs_rbf, cv = 5, scoring = 'accuracy', n_jobs=-1)
#grid_search_rbf.fit(train_feature_matrix, train_labels)

In [40]:
# Fitting not preproccesed data

svm_rbf.fit(train_feature_matrix, train_labels)

D:\Anaconda\lib\site-packages\sklearn\svm\base.py:244: ConvergenceWarning: Solver terminated early (max_iter=20000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=3, kernel='rbf',
  max_iter=20000, probability=False, random_state=None, shrinking=True,
  tol=0.0001, verbose=False)

In [41]:
# Score for test (Accuracy and F1-score)

svm_rbf.score(train_feature_matrix, train_labels)

0.935240910850667

In [42]:
svm_rbf.score(test_feature_matrix, test_labels)

0.7099483810417644

Interesting result

#### Method 4: Gradient boosting

In [50]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [51]:
# Making

Gradboost = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=15),
    n_estimators=1000,
    random_state=42)

In [52]:
# Fitting not preproccesed data

Gradboost.fit(train_feature_matrix, train_labels)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=15,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=1000, random_state=42)

In [53]:
# Score for test (Accuracy and F1-score)

accuracy_log = Gradboost.score(test_feature_matrix, test_labels)

prediction = Gradboost.predict(test_feature_matrix)

f_1 = f1_score(prediction, test_labels)

print('Acuracy = '+str(accuracy_log))
print('F1 score  = '+str(f_1))

Acuracy = 0.8125762552792116
F1 score  = 0.8724124712496806


In [54]:
print(classification_report(test_labels, prediction, labels=[0, 1]))

              precision    recall  f1-score   support

           0       0.73      0.58      0.65      6330
           1       0.84      0.91      0.87     14980

   micro avg       0.81      0.81      0.81     21310
   macro avg       0.79      0.74      0.76     21310
weighted avg       0.81      0.81      0.81     21310

